on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: teamhava/hava-sync-action@v1
        with:
          source_id: ${{ secrets.HAVA_SOURCE_ID }}
          hava_token: ${{ secrets.HAVA_API_TOKEN }}
          environment_id: ${{ secrets.HAVA_ENV_ID }}
          view_type: "infrastructure"
          image_path: "doco/diagram.png"
          skip_export: false
      - uses: stefanzweifel/git-auto-commit-action@v4